### ISSUE TITLE
로그인 시점에 이미 포인트가 마이너스가 되면 아무것도 삭제 안했는데 삭제 종료함

### ISSUE THREAD

**Issue by wi030730** [DPS0340/CleanerBot#10]
ㅈㄱㄴ

**Comment by DPS0340** [comment]
아카라이브 시스템상 글, 댓글 삭제에 포인트가 소모되며 포인트가 마이너스 상태일 시 서버가 삭제 리퀘스트를 거부하도록 설계(429 Too Many Requests 응답)되었으므로, 이것을 염두해두고 설계한 정상적인 동작입니다.

**Comment by wi030730** [comment]
아카라이브 댓글만 삭제되게 못함? 글고 글쓴이가 삭제 못하는 게시글 껴있으면 포인트 있어도 삭제 안되는듯

**Comment by DPS0340** [comment]
넹 두개 시간날때 작업해볼게용
