### ISSUE TITLE
아카 댓글 삭제가 안됨...

### ISSUE THREAD

**Issue by wi030730** [DPS0340/CleanerBot#14]
포스트 삭제는 되는데 코멘트, 글댓 합쳐서 삭제하는건 작동을 안함...

**Comment by wi030730** [comment]
포인트는 충분하고 부계정으로도 써봤음 댓삭제가 작동을 안함... 그리고 마이너스 포인트일때도 게시글 삭제 되는데 왜막아놓은거에요??

**Comment by DPS0340** [comment]
아하.. 429가 포인트 문제가 아니고 캡챠 문제였네요. 확인해서 조치하겠습니다

**Comment by DPS0340** [comment]
글댓 삭제도 테스트해볼게요

**Comment by DPS0340** [comment]
일단 글/댓글은 문제없이 작동합니다. 캡챠를 수동으로 푸는 요청도 추가했어요

**Comment by DPS0340** [comment]
#15

**Comment by wi030730** [comment]
댓글 삭제 돌릴때마다 캡챠라고 하면서 삭제확인창으로만 넘어가유 하나하나 다 그렇게 작동하는디

**Comment by DPS0340** [comment]
삭제버튼 누르고 캡챠 풀으셔도 그런가요?

**Comment by DPS0340** [comment]
> 삭제버튼 누르고 캡챠 풀으셔도 그런가요?

이렇다면 아카측에서 막아둔거같아요.

**Comment by wi030730** [comment]
캡챠가 아예 안뜸 캡챠떳다고 들어가서 링크가보면 삭제하시겠습니까 확인 창 있고 삭제한다음 이모지 누르면 다음 댓글에도 그렇게 뜸

**Comment by wi030730** [comment]
몇시간 간격들여하면 정상작동 하다가 또 이러네 글고 등록했던 아카콘도 밀어버리는 기능 없을까 ㅎㅎ;;

**Comment by DPS0340** [comment]
지금 IP 기준으로 캡챠가 작동해서 프록시 서버 API 하나 만들었어요. PR 올리겠습니다

**Comment by DPS0340** [comment]
#16

**Comment by DPS0340** [comment]
> 글고 등록했던 아카콘도 밀어버리는 기능 없을까 ㅎㅎ;;

시간날때 해볼게요~

**Comment by hercules713** [comment]
처음 뵙겠습니다. 상담 가능한가요?

**Comment by berryloverowl** [comment]
> 포스트 삭제는 되는데 코멘트, 글댓 합쳐서 삭제하는건 작동을 안함...

포스트 삭제되게 작동 어떻게 하셨나요?
