### ISSUE TITLE
캡챠 발생

### ISSUE THREAD

**Issue by minikupa** [DPS0340/CleanerBot#9]
캡챠 발생이라는 문구가 계속 뜹니다. 안내되는 대로 주소로 가서, 직접 삭제 버튼을 클릭하고 캡챠를 풀어도 똑같이 뜹니다.

**Comment by DPS0340** [comment]
로컬에서 돌리니 캡챠가 많이 발생하지 않는 것을 보니 디시인사이드 쪽에서 조치를 해두었을 가능성이 있을 것 같은데요.. 일단 확인해보겠습니다.

**Comment by DPS0340** [comment]
MITM 방식으로 수정했습니다~
